### PR TITLE
Update to optiver

### PR DESCRIPTION
**Pull request by Martje55555**
There are now multiple positions available for Summer 2022. Quick update to link to those positions.

### CODE REVIEW

**Comment by BenjaminCHEN2016** [comment]
They don't sponsor visas though...

`Legal authorization to work in the U.S. is required; we will not sponsor individuals for employment authorization for this job opening`

**Comment by Martje55555** [comment]
> They don't sponsor visas though...
> 
> `Legal authorization to work in the U.S. is required; we will not sponsor individuals for employment authorization for this job opening`

Oh my bad, didn't know that was a requirement. The previous position linked also didn't sponsor visas, so I thought that was fine.

**Comment by BenjaminCHEN2016** [comment]
> > They don't sponsor visas though...
> > `Legal authorization to work in the U.S. is required; we will not sponsor individuals for employment authorization for this job opening`
> 
> Oh my bad, didn't know that was a requirement. The previous position linked also didn't sponsor visas, so I thought that was fine.

Oh just mentioning here, better add them to the "Notes" column

**Comment by Martje55555** [comment]
> > > They don't sponsor visas though...
> > > `Legal authorization to work in the U.S. is required; we will not sponsor individuals for employment authorization for this job opening`
> > 
> > 
> > Oh my bad, didn't know that was a requirement. The previous position linked also didn't sponsor visas, so I thought that was fine.
> 
> Oh just mentioning here, better add them to the "Notes" column

Done!

**Comment by EParmar18** [comment]
Thanks!

**Pull request merged**
