### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rkabita**

### CODE REVIEW

**Comment by owini** [comment]
Thank you!

**Comment by monishshah18** [comment]
@rkabita @owini I don't see any internship openings for the mentioned position(Software Engineering or Data Analyst). Can the exact link be provided or any help for the same would be great?

**Comment by rkabita** [comment]
Hi Monish,
The same page that was mentioned will be updated when they start accepting applications.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Zmwang622** [comment]
I vote we revoke the PR and wait until the application is open. Thoughts?

**Comment by rkabita** [comment]
Sounds fair.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
