### PR TITLE
Added TikTok and ByteDance positions

### PR DESCRIPTION
**Pull request by bekadeveloper**

### CODE REVIEW

**Comment by monishshah18** [comment]
@bekadeveloper Are these positions for 2022 and for US? As these seems for different Countries and also not for 2022.

**Comment by Zmwang622** [comment]
Looks like there aren't any US postings

**Comment by DeveloperRyan** [comment]
Accidentally applied to Singapore... Lets see how this goes.

**Comment by bekadeveloper** [comment]
> Looks like there aren't any US postings

But I didn't notice anywhere that this repo only tracks US positions ...

**Pull request closed without merging**
