### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yiyangiliu**
update amazon summer 2022 internship: https://www.amazon.jobs/en/jobs/1557929/software-development-engineer-internship-summer-2022-us

### CODE REVIEW

**Comment by monishshah18** [comment]
I am not able to register for this account. I mean I didn't received any confirmation email after registering at Amazon student account. Anyone facing the same issue?

**Comment by monishshah18** [comment]
Did anyone faced Broken link issue while applying for above Amazon SDE Internship role?

**Comment by EParmar18** [comment]
I think you may be having an issue with your account creation, the link for the positions seems to be functional

**Comment by monishshah18** [comment]
@EParmar18 I got my account created and above link is also functional. But when you apply for above position, after filling General Questions section, next page does not show up instead throws Error 500.

**Comment by EParmar18** [comment]
@monishshah18 I just went through the application and was able to get past the general questions section, I would contact amazon support for the issue as it seems it may just be specific to you

**Comment by monishshah18** [comment]
Did you filled all the details or you just navigated all the sections, since issue comes on submitting that particular section?

**Pull request merged**
