### PR TITLE
Add IMC positions

### PR DESCRIPTION
**Pull request by zspherez**

### CODE REVIEW

**Comment by monishshah18** [comment]
@zspherez There is too much diff in the PR other than IMC Position being added, Can you please validate that and add just the IMC Position?

**Comment by zspherez** [comment]
> @zspherez There is too much diff in the PR other than IMC Position being added, Can you please validate that and add just the IMC Position?

It matches up exactly except IMC on my end, thinking it was just a glitch with me using CRLF line endings instead of just LF. Let me know if it still doesn't look right.

**Comment by zspherez** [comment]
> @zspherez There is too much diff in the PR other than IMC Position being added, Can you please validate that and add just the IMC Position?

@monishshah18 It matches up exactly except IMC on my end, thinking it was just a glitch with me using CRLF line endings instead of just LF. Let me know if it still doesn't look right.

**Comment by Zmwang622** [comment]
Cool, I think your editor removed the trailing white spaces too lmao

**Comment by zspherez** [comment]
Yeah seems like it... I used atom which I use all the time so its weird that its having all these problems. Checking it on https://github.com/zspherez/Summer2022-Internships/tree/add-imc it all looks the same so I'm stumped

**Comment by monishshah18** [comment]
> Yeah seems like it... I used atom which I use all the time so its weird that its having all these problems. Checking it on https://github.com/zspherez/Summer2022-Internships/tree/add-imc it all looks the same so I'm stumped

This minute changes it won't show there and aren't visible much.

**Comment by GintasS** [comment]
But I guess we better not include them. Can you quickly create a new branch from master and paste that internship position? Would merge it right away.

**Comment by Jashann** [comment]
Could you suggest me resources where I could keep track of interns positions available in Canada?

**Comment by zspherez** [comment]
Opened #388 which corrects the large diff problems.

**Pull request closed without merging**
