### PR TITLE
Added an entry for VeriSign

### PR DESCRIPTION
**Pull request by qc542**

### CODE REVIEW

**Comment by Zmwang622** [comment]
@qc542 thank you for all the work! In the future can you please put all changes in one PR? Makes it easier to approve

**Comment by qc542** [comment]
> @qc542 thank you for all the work! In the future can you please put all changes in one PR? Makes it easier to approve

@Zmwang622 You're welcome. The other day someone else told me there were too many commits in one PR and asked me to create one PR for every commit. What exactly should I do going forward?

**Comment by ducdoan510** [comment]
@qc542  I think proper ways should be something in the middle. If the change is like adding notes, we can bundle tgt in one commit.
For adding new job posting, I think we should limit to a maximum of maybe 5 jobs with one job per commit in the PR and if possible don't mix with note adding commit. The reason is that when others want to add a new listing, they can at least go through the pending PR to see if someone else is already adding it to avoid duplication. 
if the PR title is just adding one company while there are multiple inside, ppl sometimes miss it

**Comment by GintasS** [comment]
The position that you've added is closed, closing this PR.

**Comment by GintasS** [comment]
> @qc542 I think proper ways should be something in the middle. If the change is like adding notes, we can bundle tgt in one commit/PR. And I think it's good to have notes but we don't need to be too detailed because students should also do read the JDs :))
> For adding new job posting, I think we should limit to a maximum of maybe 5 jobs with one job per commit in the PR and if possible don't mix with note adding commit. The reason is that when others want to add a new listing, they can at least go through the pending PR to see if someone else is already adding it to avoid duplication.
> if the PR title is just adding one company while there are multiple inside, ppl sometimes miss it

Regarding your comment, I totally approve, especially for the title/note. If you add companies, name it as adding companies. If you edit something, like add some misc notes, name it accordingly, so we wouldn't get a mixed PR with new companies and some fixes.

**Pull request closed without merging**
