### PR TITLE
Reorder Internships Alphabetically

### PR DESCRIPTION
**Pull request by mghalayini**
Hey! I figured we'd order the internships by name, so that people searching for a specific internship would find it faster than they would by scanning the whole list from top to bottom :)

### CODE REVIEW

**Comment by ducdoan510** [comment]
But if we sort alphabetically, we might not know what new internships have been added recently, e.g., compare to the last time we visited the page (at least that what's I do, look at some bottom rows), or probably added **Updated Date** column also?

**Comment by mghalayini** [comment]
You can always browse through the history of commits to see if any new internships have been added. But yes -- I guess that might be a disadvantage for people who are not very familiar with GitHub.

**Comment by peshevv** [comment]
I agree with @ducdoan510, Finding a specific internship isn’t that difficult when you can just search the page. It’s a pain to have to look at the commit history and find out which internships were most recently added, even if you do know how to use GitHub.

**Comment by visheshdembla** [comment]
Seconding @ducdoan510 . As someone who checks the repo regularly, I just scroll to the bottom and apply to a position that I might not have applied to. If the repository is changed to contain the list in an alphabetically sorted order, that would add multiple steps to just finding the last updated listings. 

Also, imagine scenarios where the listings were added across multiple commits. That would require going through the history and figure out till when a person has applied.

Instead of alphabetical sorting, would it make more sense to keep the latest ones at the top instead?

That way, users just have to open the page and the most recent ones are already at the top!

**Comment by EParmar18** [comment]
It seems like the consensus is that alphabetical isn't as useful as the current method. I really appreciate you taking the time out to go and put them in alphabetical order though @mghalayini ! For @visheshdembla that could be a good change just have to make sure people follow that rule when they PR. @Zmwang622 any thoughts on changing the most recent to the top?

**Comment by Zmwang622** [comment]
This topic has been brought up in #159, #116, and #84 (as well as other internal discussions and issues/PRs that I can't find). For now I'd prefer we stick with the order that we've had.

**Pull request closed without merging**
