### PR TITLE
Adding DSG, Citibank

### PR DESCRIPTION
**Pull request by zspherez**

### CODE REVIEW

**Comment by EParmar18** [comment]
I don't know if its just my previewer but it looks like the last three positions are all in the same box

**Comment by monishshah18** [comment]
Also Box Opening is not for summer 2022.

**Comment by zspherez** [comment]
@EParmar18 thinking its just your previewer, looks fine at https://github.com/zspherez/Summer2022-Internships/adding-positions. Also removed box opening @monishshah18

**Comment by EParmar18** [comment]
Looks good, thanks!

**Pull request merged**
