### PR TITLE
Adding hirevue information to Morgan Stanley Summer Analyst Program

### PR DESCRIPTION
**Pull request by Tuong328**
After completing my application I noticed that I only had 72 hours to complete my HireVue, so it would be good for other applicants to know this before applying.

### CODE REVIEW

**Comment by EParmar18** [comment]
Good note, Thanks!

**Comment by monishshah18** [comment]
@EParmar18 Can you revert this PR as this has added unnecessary files also.

**Comment by EParmar18** [comment]
@monishshah18 good catch, thanks Monish

**Comment by Tuong328** [comment]
Oops, Sorry! Thanks for fixing it!

**Pull request merged**
