### PR TITLE
Add Summer Internships

### PR DESCRIPTION
**Pull request by ankasengupta**

### CODE REVIEW

**Comment by Zmwang622** [comment]
are we sure that these positions are for CS students or for Bankers?

**Comment by monishshah18** [comment]
For Goldman it shows for CS Students too, since in application details CS was there as Stream/Option.

**Comment by visheshdembla** [comment]
I filled the application for Goldman. It does have questions in the application form to indicate whether I am interested in Software Engineering or Quant positions, or both. I don't know if this helps.

**Comment by Zmwang622** [comment]
Thanks @monishshah18  and @visheshdembla that's super helpful! I can vet the other two positions if i have time tonight

**Comment by monishshah18** [comment]
@Zmwang622 Blackrock too is for Summer 2022 only, but only those can apply if they have <=18 months of work exp.(Internship+full time).

**Comment by GintasS** [comment]
**Blackrock:**

image

**Goldman:**

image

**Bank of America:**

image

**Comment by GintasS** [comment]
> Thanks @monishshah18 and @visheshdembla that's super helpful! I can vet the other two positions if i have time tonight

Merging this one, as everything is sound, hopefully you don't mind :)

**Comment by Zmwang622** [comment]
Yup sounds good. Thanks Gintautas

**Pull request merged**
