### PR TITLE
Add Twitch

### PR DESCRIPTION
**Pull request by nkalupahana**

### CODE REVIEW

**Comment by rndev2017** [comment]
Not sure if this is the best outlet to bring up this issue, but it seems like the Twitch link doesn't actually contain the job posting. I added a screenshot when I click the link from the GitHub page. Any help would be appreciated!

image

**Comment by nkalupahana** [comment]
It was working two days ago -- it looks like they've taken the job posting down 👀 either it was last year's, or they're already full? For now, though, it should probably be removed.

**Comment by ducdoan510** [comment]
Hmm, this also happened with Uber when the job posting was only around for like 1-2 days. Maybe they need to do some modifications to the JD and will post again at a later time. Finger crossed :x

**Comment by pratyaksh123** [comment]
I was surprised when twitch removed this listing just after 2 days, i thought I missed it 👀

**Pull request merged**
