### PR TITLE
Add Apple ML/AI

### PR DESCRIPTION
**Pull request by robbyhorvath**

### CODE REVIEW

**Comment by EParmar18** [comment]
Could you put both the links into one listing?

**Comment by robbyhorvath** [comment]
Combined the two listings.

**Comment by ducdoan510** [comment]
Does this make sense to move both listings to the bottom as a new update because people might not pay attention that Apple opening has changed?

**Comment by GintasS** [comment]
Are these actually for Summer 2022? I can't see anywhere in the postings where it says that it is for Summer 2022.

**Comment by robbyhorvath** [comment]
I found the ML/AI when I was applying to the SWE posting that was already present: I just assumed it was also Summer 2022.

**Pull request closed without merging**
